const DirectoryActionTypes = {
  UPDATE_SECTIONS: "UPDATE_SECTIONS",
  FETCH_SECTIONS_START: "FETCH_SECTIONS_START",
  FETCH_SECTIONS_SUCCESS: "FETCH_SECTIONS_SUCCESS",
  FETCH_SECTIONS_FAILURE: "FETCH_SECTIONS_FAILURE"
}
export default DirectoryActionTypes;