const OrdersActionTypes = {
  FETCH_ORDERS_START: "FETCH_ORDERS_START",
  FETCH_ORDERS_SUCCESS: "FETCH_ORDERS_SUCCESS",
  FETCH_ORDERS_FAILURE: "FETCH_ORDERS_FAILURE",
  CLEAR_ORDERS: "CLEAR_ORDERS"
}
export default OrdersActionTypes;